### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by erhn67** [OfekHarel/HorizonMusic#5]
Some files are missing.  How can I access the missing files?  Can you help me?  Is there an e-mail address or telephone number to contact?

**Comment by OfekHarel** [comment]
Yeah sure :-)

The release version 1.1.0 contains a zip folder (called HorizonMusic.zip). 
There you can find all the project files and run the project.
FYI - This project made for private use there for it doesn't have a public server... so if you want to run the project contact me for more info.

BTW why are you interested?
Here is my email: **ofekizh@gmail.com**
